version: "3.7"

services:
  gizh_postgres_database:
    image: postgres
    container_name: postgres_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgresDB
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: gizh
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - gizh_postgres_database
    depends_on:
      - gizh_postgres_database

volumes:
  pgdata:
    driver: local
